### ISSUE TITLE
Loading TAS replay misses first input frame

### ISSUE THREAD

**Issue by AlexMorson** [msg555/dustmaker#7]
When loading TAS replays with dustmaker, the first frame of input is lost.

Looking at <https://dustkid.com/replay/-10348443/showinputs> we can see that there are 55 leading `0`s in the dash intent stream.
But, when loading the replay file with dustmaker, the dash intent stream only contains 54 leading `0`s:
```Python
>>> import dustmaker  # Version 1.1.0
>>> with open("-10348443.dfreplay", "rb") as file:
...     reader = dustmaker.DFReader(file)
...     replay = reader.read_replay()
...     print(replay.players[0].intents[3].index(1)
54
```

All other TAS replays that I have tested exhibit this behaviour, and all non-TAS replays that I have tested do not.

**Comment by msg555** [comment]
Thanks for the report, can confirm I get the same behavior. Sounds like a difference in how dustkid writes the replay files that is being interpretted differently by dustmaker.

**Comment by msg555** [comment]
https://github.com/msg555/dustmaker/commit/79bbaf8a37d17b8b442fb58d4cd86b313772e7fd should fix
